---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./sonarr:/config
      - ./downloads/tvseries:/tv
      - ./downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./radarr:/config
      - ./downloads/movies:/movies
      - ./downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    volumes:
      - ./qbit:/config
      - ./downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped
    
    
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./jackett:/config
      - ./downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

   rclone:
    image: rclone/rclone
    container_name: rclone
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./rclone:/config/rclone
      - ./mydata:/mydata
    ports:
      - 5572:5572
    restart: unless-stopped
 
